### ISSUE TITLE
Wraithverge crashes Hexen on amd64 FreeBSD

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#317]
Bug report received by email from Jakub Lach. gdb backtrace:

```
(gdb) bt
#0  CHolySeekerMissile (turnMax=381774848, thresh=190887424, actor=0x803325b90) at p_pspr.c:2002
#1  A_CHolySeek (actor=0x803325b90) at p_pspr.c:2108
#2  0x000000000042006b in P_SetMobjState (mobj=mobj@entry=0x803325b90, state=<optimized out>)
   at p_mobj.c:114
#3  0x0000000000421e16 in P_MobjThinker (mobj=0x803325b90) at p_mobj.c:1163
#4  0x000000000042a4cf in RunThinkers () at p_tick.c:110
#5  P_Ticker () at p_tick.c:83
#6  0x000000000043f307 in G_Ticker () at g_game.c:1004
#7  0x000000000043c770 in RunTic (cmds=0x6c1860 <ticdata+10240>, ingame=0x6c18e0 <ticdata+10368>)
   at d_net.c:101
#8  0x0000000000405a90 in TryRunTics () at d_loop.c:793
#9  0x0000000000419ed9 in H2_GameLoop () at h2_main.c:635
#10 0x000000000041a7d5 in D_DoomMain () at h2_main.c:421
#11 0x0000000000403d02 in main (argc=<optimized out>, argv=<optimized out>) at i_main.c:152
```

**Comment by jmtd** [comment]
@CapnClever points out that this has almost certainly been fixed by #577, closing (without confirming), but can be re-opened if we're wrong.
