### ISSUE TITLE
Address sanitizer issues...

### ISSUE THREAD

**Issue by edward-san** [chocolate-doom/chocolate-doom#536]
Premise: in order to use the address sanitizer, you must fix a mistake from ```sdl.m4```, which is that the source used to test the sdl version conformance, which is:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL.h"

char*
my_strdup (char *str)
{
  char *new_str;
  
  if (str)
    {
      new_str = (char *)malloc ((strlen (str) + 1) * sizeof(char));
      strcpy (new_str, str);
    }
  else
    new_str = NULL;
  
  return new_str;
}

int main (int argc, char *argv[])
{
  int major, minor, micro;
  char *tmp_version;

  /* This hangs on some systems (?)
  system ("touch conf.sdltest");
  */
  { FILE *fp = fopen("conf.sdltest", "a"); if ( fp ) fclose(fp); }

  /* HP/UX 9 (%@#!) writes to sscanf strings */
  tmp_version = my_strdup("$min_sdl_version");
  if (sscanf(tmp_version, "%d.%d.%d", &major, &minor, &micro) != 3) {
     printf("%s, bad version string\n", "$min_sdl_version");
     exit(1);
   }

   if (($sdl_major_version > major) ||
      (($sdl_major_version == major) && ($sdl_minor_version > minor)) ||
      (($sdl_major_version == major) && ($sdl_minor_version == minor) && ($sdl_micro_version >= micro)))
    {
      return 0;
    }
  else
    {
      printf("\n*** 'sdl-config --version' returned %d.%d.%d, but the minimum version\n", $sdl_major_version, $sdl_minor_version, $sdl_micro_version);
      printf("*** of SDL required is %d.%d.%d. If sdl-config is correct, then it is\n", major, minor, micro);
      printf("*** best to upgrade to the required version.\n");
      printf("*** If sdl-config was wrong, set the environment variable SDL_CONFIG\n");
      printf("*** to point to the correct copy of sdl-config, and remove the file\n");
      printf("*** config.cache before re-running configure\n");
      return 1;
    }
}
```

does not free ```tmp_version``` before exiting, hence the leak sanitizer pops in and makes the test fail. if you add ```free(tmp_version);``` before ```if (($sdl_major_version > major) ||```, it can configure well.

After this premise, after compiling chocolate-doom with ```-fsanitize=address```, run it with DOOM2.WAD, watch the 3rd demo in map26. The address sanitizer will kick in when the player is in the external area, with imps and lost souls, above the barrels and the mancubus. This is what it reports:

```
==15954==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000006a7564 at pc 0x000000610c4a bp 0x7ffda4985780 sp 0x7ffda4985778
READ of size 4 at 0x0000006a7564 thread T0
    #0 0x610c49 in R_RenderSegLoop /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_segs.c:257:41
    #1 0x6195c4 in R_StoreWallRange /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_segs.c:711:5
    #2 0x653a69 in R_ClipPassWallSegment /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:230:5
    #3 0x654d64 in R_AddLine /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:344:5
    #4 0x656478 in R_Subsector /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:532:2
    #5 0x6564e1 in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:556:6
    #6 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #7 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #8 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #9 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #10 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #11 0x6566db in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:570:2
    #12 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #13 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #14 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #15 0x6566db in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:570:2
    #16 0x65664c in R_RenderBSPNode /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_bsp.c:566:5
    #17 0x60a76b in R_RenderPlayerView /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_main.c:877:5
    #18 0x5643be in D_Display /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/d_main.c:245:2
    #19 0x565803 in D_DoomLoop /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/d_main.c:455:13
    #20 0x56adc4 in D_DoomMain /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/d_main.c:1832:5
    #21 0x4e3f4b in main /home/edward-san/chocolate-doom/trunk/build/src/../../src/i_main.c:48:5
    #22 0x7f1397473ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287
    #23 0x42f7d5 in _start (/home/edward-san/chocolate-doom/trunk/build/src/chocolate-doom+0x42f7d5)

0x0000006a7564 is located 4 bytes to the right of global variable 'finetangent' defined in '../../src/tables.c:64:11' (0x6a3560) of size 16384
SUMMARY: AddressSanitizer: global-buffer-overflow /home/edward-san/chocolate-doom/trunk/build/src/doom/../../../src/doom/r_segs.c:257:41 in R_RenderSegLoop
Shadow bytes around the buggy address:
  0x0000800cce50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800cce60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800cce70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800cce80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800cce90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0000800ccea0: 00 00 00 00 00 00 00 00 00 00 00 00[f9]f9 f9 f9
  0x0000800cceb0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0000800ccec0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0000800cced0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0000800ccee0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x0000800ccef0: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==15954==ABORTING
```
Essentially, ```finetangent``` was accessed with index ```4097```, which is outside the ```[0:4095]``` bounds.

You can get a similar result if you run plutonia.wad, first demo, when the player presses the second switch in the open area. In that case, the index is ```4096```, still outside the bounds.

**Comment by haleyjd** [comment]
http://www.doomworld.com/vb/source-ports/54242-the-shady-segtextured-overflow/

**Comment by fabiangreffrath** [comment]
Maybe we can emulate the overflow like this, taken that finesine[] follows finetangent[] in the DOS executable:
```
--- a/src/doom/r_segs.c
+++ b/src/doom/r_segs.c
@@ -254,7 +254,10 @@ void R_RenderSegLoop (void)
        {
            // calculate texture offset
            angle = (rw_centerangle + xtoviewangle[rw_x])>>ANGLETOFINESHIFT;
+           if (angle < arrlen(finetangent))
            texturecolumn = rw_offset-FixedMul(finetangent[angle],rw_distance);
+           else
+           texturecolumn = rw_offset-FixedMul(finesine[angle-arrlen(finetangent)],rw_distance);
```

**Comment by haleyjd** [comment]
It'd arguably be simpler to extend finetangent with some of the contents of finesine so that it is oversized and therefore tolerates the overflow naturally; however, it's difficult to figure out what the max overflow index is and you clearly don't want to duplicate the entire table. So I dunno.
