### ISSUE TITLE
chocolate-hexen: Random segfault with Wraithverge

### ISSUE THREAD

**Issue by g6672D** [chocolate-doom/chocolate-doom#573]
To reproduce: Well, it's basically as the title says: Shoot a group of enemies with it a bunch and "hope" it crashes. I used MAP02 or MAP11 to test on. Traductus can also do it.

Reproduced in 2.2.0 built normally and Git without optimizations. Backtrace from the latter:

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000043ba30 in CHolySeekerMissile (actor=0x7fffeefa2c88, thresh=119304640, turnMax=238609280) at p_pspr.c:1994
1994	    if (!(target->flags & MF_SHOOTABLE)
(gdb) backtrace
#0  0x000000000043ba30 in CHolySeekerMissile (actor=0x7fffeefa2c88, thresh=119304640, turnMax=238609280) at p_pspr.c:1994
#1  0x000000000043bf64 in A_CHolySeek (actor=0x7fffeefa2c88) at p_pspr.c:2100
#2  0x00000000004305a5 in P_SetMobjState (mobj=0x7fffeefa2c88, state=S_HOLY_FX2) at p_mobj.c:106
#3  0x000000000043260b in P_MobjThinker (mobj=0x7fffeefa2c88) at p_mobj.c:1155
#4  0x000000000044180f in RunThinkers () at p_tick.c:104
#5  0x000000000044176c in P_Ticker () at p_tick.c:75
#6  0x0000000000460555 in G_Ticker () at g_game.c:1054
#7  0x000000000045ddd7 in RunTic (cmds=0x6f45a0 <ticdata+4640>, ingame=0x6f4620 <ticdata+4768>) at d_net.c:95
#8  0x000000000040696f in TryRunTics () at d_loop.c:803
#9  0x0000000000428f97 in H2_GameLoop () at h2_main.c:751
#10 0x0000000000428b8b in D_DoomMain () at h2_main.c:519
#11 0x0000000000403bd3 in main (argc=3, argv=0x7fffffffe2c8) at i_main.c:48
```

**Comment by g6672D** [comment]
Referenced issue seems to have fixed the problem, so I'll close this. Also apologies for the duplicate bug report.

**Comment by fragglet** [comment]
No problem, thank you for the fix!
